parameters:
    leapt_i18n.locales: ~
    leapt_i18n.routing.translation_domain: ~

services:
    leapt_i18n:
        class: Leapt\I18nBundle\Registry
        arguments: [ "%leapt_i18n.locales%" ]

    leapt_i18n.twig:
        class: Leapt\I18nBundle\Twig\Extension\LocaleExtension
        arguments: [ "@request_stack", "@leapt_i18n" ]
        tags:
            - { name: twig.extension }

    leapt_i18n.routing_router:
        class: Leapt\I18nBundle\Routing\I18nRouter
        parent: router.default
        public: false
        calls:
            - [ "setRegistry", [ "@leapt_i18n" ] ]

    leapt_i18n.routing_loader_helper:
        class: Leapt\I18nBundle\Routing\I18nLoaderHelper
        arguments: [ "@translator.default", "%leapt_i18n.routing.translation_domain%" ]

    leapt_i18n.routing_loader_class:
        class: Leapt\I18nBundle\Routing\I18nAnnotatedRouteControllerLoader
        arguments: [ "@annotation_reader", "@leapt_i18n.routing_loader_helper", "@leapt_i18n" ]
        tags:
            - { name: routing.loader }

    leapt_i18n.routing_loader_annotation_directory:
        class: Leapt\I18nBundle\Routing\I18nAnnotationDirectoryLoader
        arguments: [ "@file_locator", "@leapt_i18n.routing_loader_class" ]
        tags:
            - { name: routing.loader }

    leapt_i18n.routing_loader_annotation_file:
        class: Leapt\I18nBundle\Routing\I18nAnnotationFileLoader
        arguments: [ "@file_locator", "@leapt_i18n.routing_loader_class" ]
        tags:
            - { name: routing.loader }

    leapt_i18n.routing_loader_yaml:
        class: Leapt\I18nBundle\Routing\I18nYamlFileLoader
        arguments: [ "@file_locator", "@leapt_i18n.routing_loader_helper", "@leapt_i18n" ]
        tags:
            - { name: routing.loader }