parameters:
    snowcap_i18n.locales: ~
    snowcap_i18n.routing.translation_domain: ~

services:
    snowcap_i18n:
        class: Snowcap\I18nBundle\Registry
        arguments: [%snowcap_i18n.locales%]

    snowcap_i18n.twig:
        class: Snowcap\I18nBundle\Twig\Extension\LocaleExtension
        arguments: [@service_container, @snowcap_i18n]
        tags:
            - { name: twig.extension }

    snowcap_i18n.routing_loader_helper:
        class: Snowcap\I18nBundle\Routing\I18nLoaderHelper
        arguments: [@translator, %snowcap_i18n.routing.translation_domain%]

    snowcap_i18n.routing_loader_class:
        class: Snowcap\I18nBundle\Routing\I18nClassLoader
        arguments: [@annotation_reader, @snowcap_i18n.routing_loader_helper, @snowcap_i18n]
        tags:
            - { name: routing.loader }

    snowcap_i18n.routing_loader_directory:
        class: Snowcap\I18nBundle\Routing\I18nDirectoryLoader
        arguments: [@file_locator, @snowcap_i18n.routing_loader_class]
        tags:
            - { name: routing.loader }

    snowcap_i18n.routing_loader_yaml:
        class: Snowcap\I18nBundle\Routing\I18nYamlFileLoader
        arguments: [@file_locator, @snowcap_i18n.routing_loader_helper, @snowcap_i18n]
        tags:
            - { name: routing.loader }